{% set name = "titiler-core" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/titiler.core-{{ version }}.tar.gz
  sha256: fa854dad7768025d58cb5d6123df9ed24582a50141b1b7e87ed7c062c953e6d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - async-exit-stack >=1.0.1,<2.0.0
    - async_generator >=1.10,<2.0.0
    - dataclasses
    - fastapi >=0.65,<0.68
    - geojson-pydantic
    - importlib_resources >=1.1.0
    - jinja2 >=2.11.2,<3.0.0
    - morecantile <3.0.0
    - numpy
    - pydantic
    - python >=3.6
    - rasterio
    - rio-tiler >=2.1,<2.2
    - simplejson

test:
  imports:
    - titiler
    - titiler.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/developmentseed/titiler
  summary: A modern dynamic tile server built on top of FastAPI and Rasterio/GDAL.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rsignell-usgs
