{% set name = "titiler-core" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/titiler.core-{{ version }}.tar.gz
  sha256: 113f60abb2e2dc249cf735bd13e4e7e2c2e59a73492a86cfe93cc3b5379b59d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pdm-pep517
    - pip
    - python >=3.8
  run:
    - fastapi >=0.100.0
    - geojson-pydantic >=1.0,<2.0
    - jinja2 >=2.11.2,<4.0.0
    - numpy
    - pydantic >=2.0,<3.dev0
    - rasterio
    - rio-tiler >=6.2.1,<7.0
    - morecantile >=5.0,<6.0
    - simplejson
    - typing_extensions >=4.6.1
    - python >=3.8
test:
  imports:
    - titiler
    - titiler.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/developmentseed/titiler
  summary: A modern dynamic tile server built on top of FastAPI and Rasterio/GDAL.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tylere
    - rsignell-usgs
