{% set name = "titiler-core" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/titiler_core-{{ version }}.tar.gz
  sha256: 704d8801affc5f70a24fb19b9c378489b3e8d7b3efd77ecf6544a04ee882a0e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pdm-pep517
    - pip
    - python {{ python_min }}
  run:
    - fastapi >=0.136.1
    - geojson-pydantic >=1.1.2,<3.0
    - jinja2 >=2.11.2,<4.0.0
    - numpy
    - pydantic =2.0
    - rasterio
    - rio-tiler >=9.0,<10.0
    - morecantile
    - simplejson
    - python >={{ python_min }}
test:
  imports:
    - titiler
    - titiler.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/developmentseed/titiler
  summary: A modern dynamic tile server built on top of FastAPI and Rasterio/GDAL.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinRenou
    - tylere
    - rsignell-usgs
